spring:
  datasource:
    url: jdbc:sqlserver://your-server-name.database.windows.net:1433;database=your-database-name
    username: managed-identity-user
    password: ""
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
